"""empty message

Revision ID: 13cb3e68d8c8
Revises: cdd98233a522
Create Date: 2019-12-16 16:27:11.695428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cb3e68d8c8'
down_revision = 'cdd98233a522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('shipped', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('shipped', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('shipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'shipped')
    op.drop_column('order', 'shipped')
    op.drop_column('carts', 'shipped')
    # ### end Alembic commands ###
