"""empty message

Revision ID: 46cc8d673763
Revises: 54871effef6c
Create Date: 2019-12-22 17:09:14.324021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cc8d673763'
down_revision = '54871effef6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created')
    # ### end Alembic commands ###
