"""empty message

Revision ID: 7ac44d531a46
Revises: 9a264edd6340
Create Date: 2019-12-14 17:48:39.089060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac44d531a46'
down_revision = '9a264edd6340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'created')
    # ### end Alembic commands ###
