"""empty message

Revision ID: 8fc0b9bf7a00
Revises: b8fa69c33661
Create Date: 2019-12-09 11:15:42.619836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc0b9bf7a00'
down_revision = 'b8fa69c33661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('carts_product_id_fkey', 'carts', type_='foreignkey')
    op.drop_column('carts', 'product_id')
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('carts_product_id_fkey', 'carts', 'product', ['product_id'], ['id'])
    op.drop_table('order_items')
    # ### end Alembic commands ###
