"""empty message

Revision ID: a9927b2d06ae
Revises: 262536efc02f
Create Date: 2019-12-10 18:07:02.777401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9927b2d06ae'
down_revision = '262536efc02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
