"""empty message

Revision ID: cc0a366bbae7
Revises: c59a76d6cd7c
Create Date: 2019-12-07 03:15:24.121898

"""
from alembic import op
import sqlalchemy as sa,sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cc0a366bbae7'
down_revision = 'c59a76d6cd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_seller_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'users', ['seller_id'], ['id'])
    op.drop_column('product', 'seller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_seller_fkey', 'product', 'users', ['seller'], ['id'])
    op.drop_column('product', 'seller_id')
    # ### end Alembic commands ###
