"""empty message

Revision ID: cdd98233a522
Revises: 7ac44d531a46
Create Date: 2019-12-15 22:36:00.708856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd98233a522'
down_revision = '7ac44d531a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'seller_id')
    # ### end Alembic commands ###
